### 1. 파일 업로드
POST http://localhost:8080/api/v1/files
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="files"; filename="test1.png"
Content-Type: image/png

< ./docker.png

--WebAppBoundary--

### 2. 견적 생성
POST http://localhost:8080/api/v1/estimates
Content-Type: application/json

{
  "userId": "expert1",
  "projectNo": 1,
  "amount": "1500",
  "description": "무인카페 시설 견적서입니다. 상세 내역은 다음과 같습니다:\n1. 인테리어 공사: 800만원\n2. 설비 설치: 500만원\n3. 기타 비용: 200만원",
  "fileIds": [1]
}

### 2. expert2의 견적 제출
# 파일 업로드
POST http://localhost:8080/api/v1/files
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="files"; filename="expert2_estimate.jpg"
Content-Type: image/jpeg

< ./expert2_estimate.jpg
--WebAppBoundary--

### expert2의 견적 생성
POST http://localhost:8080/api/v1/estimates
Content-Type: application/json

{
  "userId": "expert2",
  "projectNo": 1,
  "amount": "1800",
  "description": "무인카페 시설 견적서입니다.\n1. 인테리어 공사: 1000만원\n2. 설비 설치: 600만원\n3. 기타 비용: 200만원",
  "fileIds": [2]
}

### 사용자의 진행중인 프로젝트 견적 조회
GET http://localhost:8080/api/v1/users/client2/estimates
